#:schema https://developers.openai.com/codex/config-schema.json

## https://github.com/openai/codex/blob/main/docs/config.md
approval_policy        = "on-failure"
file_opener            = "vscode-insiders"
model                  = "gpt-5.3-codex"
model_reasoning_effort = "medium"
personality            = "pragmatic"
sandbox_mode           = "workspace-write"
