[tools]
"aqua:anthropics/claude-code" = "2.1.19"
bun                           = "1.3.6"
"npm:@github/copilot"         = "0.0.394"
"npm:@google/gemini-cli"      = "0.25.2"
"npm:@openai/codex"           = "0.91.0"
"npm:ctx7"                    = "0.1.4"

[settings.aqua]
baked_registry = false ## For claude-code, it not mirror to mise registry yet

[env]
DO_NOT_TRACK = "1"
